# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 243)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 609, 201))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.widget_layout_horizontal = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.widget_layout_horizontal.setContentsMargins(9, 9, 9, 9)
        self.widget_layout_horizontal.setSpacing(6)
        self.widget_layout_horizontal.setObjectName("widget_layout_horizontal")
        self.widget_macros_list = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.widget_macros_list.setObjectName("widget_macros_list")
        self.widget_layout_horizontal.addWidget(self.widget_macros_list)
        self.widget_macro_text = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.widget_macro_text.setObjectName("widget_macro_text")
        self.widget_layout_horizontal.addWidget(self.widget_macro_text)
        self.widget_layout_vertical_buttons = QtWidgets.QVBoxLayout()
        self.widget_layout_vertical_buttons.setSpacing(6)
        self.widget_layout_vertical_buttons.setObjectName("widget_layout_vertical_buttons")
        self.widget_button_stop_running = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.widget_button_stop_running.setObjectName("widget_button_stop_running")
        self.widget_layout_vertical_buttons.addWidget(self.widget_button_stop_running)
        self.widget_button_start_running = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.widget_button_start_running.setObjectName("widget_button_start_running")
        self.widget_layout_vertical_buttons.addWidget(self.widget_button_start_running)
        self.widget_button_run_once = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.widget_button_run_once.setObjectName("widget_button_run_once")
        self.widget_layout_vertical_buttons.addWidget(self.widget_button_run_once)
        self.widget_button_save_recording = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.widget_button_save_recording.setObjectName("widget_button_save_recording")
        self.widget_layout_vertical_buttons.addWidget(self.widget_button_save_recording)
        self.widget_button_clear_recording = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.widget_button_clear_recording.setObjectName("widget_button_clear_recording")
        self.widget_layout_vertical_buttons.addWidget(self.widget_button_clear_recording)
        self.widget_button_stop_recording = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.widget_button_stop_recording.setObjectName("widget_button_stop_recording")
        self.widget_layout_vertical_buttons.addWidget(self.widget_button_stop_recording)
        self.widget_button_start_recording = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.widget_button_start_recording.setObjectName("widget_button_start_recording")
        self.widget_layout_vertical_buttons.addWidget(self.widget_button_start_recording)
        self.widget_layout_horizontal.addLayout(self.widget_layout_vertical_buttons)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_settings = QtWidgets.QMenu(self.menubar)
        self.menu_settings.setObjectName("menu_settings")
        MainWindow.setMenuBar(self.menubar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_playback_settings = QtWidgets.QAction(MainWindow)
        self.action_playback_settings.setObjectName("action_playback_settings")
        self.action_keybindings = QtWidgets.QAction(MainWindow)
        self.action_keybindings.setEnabled(False)
        self.action_keybindings.setObjectName("action_keybindings")
        self.action_save_as = QtWidgets.QAction(MainWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_save_as)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_quit)
        self.menu_settings.addAction(self.action_playback_settings)
        self.menu_settings.addAction(self.action_keybindings)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_settings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Marvelous Mechanical Mouse"))
        self.widget_button_stop_running.setText(_translate("MainWindow", "Stop running"))
        self.widget_button_start_running.setText(_translate("MainWindow", "Start running"))
        self.widget_button_run_once.setText(_translate("MainWindow", "Run once"))
        self.widget_button_save_recording.setText(_translate("MainWindow", "Save recording"))
        self.widget_button_clear_recording.setText(_translate("MainWindow", "Clear recording"))
        self.widget_button_stop_recording.setText(_translate("MainWindow", "Stop recording"))
        self.widget_button_start_recording.setText(_translate("MainWindow", "Start recording"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.menu_settings.setTitle(_translate("MainWindow", "Settings"))
        self.action_open.setText(_translate("MainWindow", "Open"))
        self.action_save.setText(_translate("MainWindow", "Save"))
        self.action_quit.setText(_translate("MainWindow", "Quit"))
        self.action_playback_settings.setText(_translate("MainWindow", "Playback settings"))
        self.action_keybindings.setText(_translate("MainWindow", "Keybindings (coming soon)"))
        self.action_save_as.setText(_translate("MainWindow", "Save As"))
        self.action_about.setText(_translate("MainWindow", "About"))

